### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by devignx**

### CODE REVIEW

**Review by Yasar195 — COMMENTED** [review]
Bro what's this for..? it is SEO

**Comment by devignx** [comment]
> Bro what's this for..? it is SEO

yes bro, I have added some meta tags to improve our sites accessiblity & a bit seo.

**Comment by devignx** [comment]
> > Bro what's this for..? it is SEO
> 
> yes bro, I have added some meta tags to improve our sites accessiblity & a bit seo.

OG tags to improve social media url previews

**Comment by Yasar195** [comment]
i have reviewed your changes. it's perfect your contribution is much appreciated.

**Pull request closed without merging**
